url: https://neuvector.github.io/neuvector-helm/core-2.8.4.tgz
version: 104.0.4
additionalCharts:
- workingDir: charts-crd
  crdOptions:
    templateDirectory: crd-template
    crdDirectory: templates
